name: gcp-prod
on:
  push:
    branches:
      - gcp-prod

jobs:
  gcp-prod:
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write
      contents: read
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Authenticate to Google Cloud using workload identity federation
    - id: 'auth'
      name: 'Obtain access token by using workload identity federation'
      uses: 'google-github-actions/auth@v0'
      
      with:
        create_credentials_file: true
        token_format: access_token
        workload_identity_provider: projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-action-sachai-pool/providers/github-action-sachai-provider
        service_account: github-action-svc@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com

    - name: Connect to Artifact Registry
      run: |-
        echo ${{ steps.auth.outputs.access_token }} | docker login -u oauth2accesstoken --password-stdin https://${{ secrets.GCP_REPOSITORY_REGION }}-docker.pkg.dev

    - name: Build Docker Image
      run: docker build -t asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/sachai-prod-infra/${{ secrets.GCP_IMAGE_NAME_PROD }}:$GITHUB_REF_NAME-$GITHUB_SHA .

    - uses: actions/checkout@v2
    - name: Set env
      run: echo "GITHUB_BRANCH=$(echo $GITHUB_REF_NAME-$GITHUB_SHA)" >> $GITHUB_ENV

    - name: Push Docker Image to Artifact Registry
      run: |-
        docker push asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/sachai-prod-infra/${{ secrets.GCP_IMAGE_NAME_PROD }}:$GITHUB_REF_NAME-$GITHUB_SHA

        git clone https://${{ secrets.AWS_GITHUB_USER }}:${{ secrets.AWS_GITHUB_TOKEN }}@github.com/wohlig/AskUs-GitOps
        cd AskUs-GitOps
        
        git checkout production

        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@wohlig.com"

        yq e '.spec.template.spec.containers[0].image = "asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/sachai-prod-infra/${{ secrets.GCP_IMAGE_NAME_PROD }}:${{ env.GITHUB_BRANCH }}"' -i deployment.apps/sachai-gpt.yaml
  
        git add .
        git commit -m "updating newer image"  
        git push --set-upstream origin production
